// Generated by CIRCT firtool-1.62.1
module Counter(
  input        clock,
               reset,
               io_en,
  output [7:0] io_out
);

  reg [7:0] cnt;
  always @(posedge clock) begin
    if (reset)
      cnt <= 8'h0;
    else if (io_en)
      cnt <= cnt + 8'h1;
  end // always @(posedge)
  assign io_out = cnt;
endmodule

